# Expresses whether a feature of the object was detected
# Features correspond to a corner or a side of the perceived object.
# The middle features (f, b, l, r) define that the side of an object in general is observed and
# does not specifically mean that the exact mid-point of the side is observed.
bool fl # Front left
bool fr # Front right
bool bl # Rear left
bool br # Rear right
bool f # Front middle
bool b # Rear middle
bool l # Middle left
bool r # Middle right
bool c # Center of the object
