<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ufil_core</name>
  <version>0.1.0</version>
  <description>Unified Framework for Infrastructure Localization (UFIL) meta package.</description>
  <maintainer email="simon.schaefer@rwth-aachen.de">Simon Schäfer</maintainer>
  <license>MIT</license>

  <depend>ufil_etsi</depend>
  <depend>ufil_message_filter</depend>
  <depend>ufil_mqtt</depend>
  <depend>ufil_osc</depend>
  <depend>ufil_msgs</depend>
  <depend>ufil_object_tracking</depend>
  <depend>ufil_ros</depend>
  <depend>ufil_udp</depend>
  <depend>ufil_visualization</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
