<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ufil_mqtt</name>
  <version>0.1.0</version>
  <description>Converts ROS 2 messages to MQTT messages.</description>
  <maintainer email="hegerath@embedded.rwth-aachen.de">Lucas Hegerath</maintainer>
  <maintainer email="schaefer@embedded.rwth-aachen.de">Simon Schäfer</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <depend>ufil_msgs</depend>
  <depend>ufil_ros</depend>

  <depend>libpaho-mqtt-dev</depend>
  <depend>libpaho-mqttpp-dev</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>