FROM ros:jazzy
ARG USERNAME
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ENV NODE_VERSION=24.13.0

ENV HOME=/home/$USERNAME
ENV NVM_DIR=$HOME/.nvm

# Delete user if it exists in container (e.g Ubuntu Noble: ubuntu)
RUN if id -u $USER_UID ; then userdel `id -un $USER_UID` ; fi

# Create the user and install dependencies in a single layer
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
    sudo \
    python3-pip \
    liboscpack-dev \
    libtbb-dev \
    libboost-dev \
    libpaho-mqttpp-dev \
    libpaho-mqtt-dev \
    build-essential \
    curl \
    git \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && rm -rf /var/lib/apt/lists/*

ENV SHELL /bin/bash

# Set default user
USER $USERNAME

# Add Node.js (latest LTS)
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash \
    && . "$NVM_DIR/nvm.sh" \
    && nvm install ${NODE_VERSION} \
    && nvm use ${NODE_VERSION} \
    && nvm alias default ${NODE_VERSION}

ENV PATH="$HOME/.nvm/versions/node/v${NODE_VERSION}/bin:${PATH}"

# Enable ROS for non-root user
RUN echo "source /opt/ros/jazzy/setup.bash" >> /home/$USERNAME/.bashrc

CMD ["/bin/bash"]