<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ufil_obu</name>
    <version>0.1.0</version>
    <description>Meta package for the OBU.</description>
    <maintainer email="hegerath@embedded.rwth-aachen.de">Lucas Hegerath</maintainer>
    <maintainer email="schaefer@embedded.rwth-aachen.de">Simon Schäfer</maintainer>
    <license>MIT</license>

    <depend>ufil_etsi</depend>
    <depend>etsi_its_conversion</depend>
    <depend>robot_localization</depend>
    <depend>udp_driver</depend>
    <depend>ufil_message_filter</depend>
    <depend>ufil_msgs</depend>
    <depend>ufil_obu_object_aggregation</depend>
    
    <buildtool_depend>ament_cmake</buildtool_depend>

    <test_depend>ament_lint_auto</test_depend>
    <test_depend>ament_lint_common</test_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
